version: "3"
services:
  app:
    image: jc21/nginx-proxy-manager:latest
    restart: always
    ports:
      - 80:80
      - 443:443
      - 81:81
    volumes:
      - ./config.json:/app/config/production.json
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    depends_on:
      - db
  db:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "Dirty3rdy!"
      MYSQL_DATABASE: "homelab_proxy"
      MYSQL_USER: "proxy-daemon"
      MYSQL_PASSWORD: "Rapeface!"
    volumes:
      - ./data/mysql:/var/lib/mysql
